// Drawing prompts for Secret Artist - Easy to identify, hard to draw well
// Each prompt has a normal version and a secret artist version (similar but different)
export const drawingPrompts = [
  // Actions & Activities
  { normal: 'Someone sleeping', secret: 'Someone resting' },
  { normal: 'Running', secret: 'Jogging' },
  { normal: 'Swimming', secret: 'Floating in water' },
  { normal: 'Dancing', secret: 'Moving to music' },
  { normal: 'Jumping', secret: 'Hopping' },
  { normal: 'Eating', secret: 'Having a snack' },
  { normal: 'Drinking', secret: 'Having a beverage' },
  { normal: 'Reading a book', secret: 'Looking at a magazine' },
  { normal: 'Watching TV', secret: 'Looking at a screen' },
  { normal: 'Playing video games', secret: 'Using a controller' },
  { normal: 'Texting on a phone', secret: 'Using a phone' },
  { normal: 'Taking a selfie', secret: 'Taking a photo' },
  { normal: 'Cooking', secret: 'Making food' },
  { normal: 'Driving a car', secret: 'Steering a vehicle' },
  { normal: 'Riding a bike', secret: 'Pedaling' },
  { normal: 'Skateboarding', secret: 'Riding a board' },
  { normal: 'Brushing teeth', secret: 'Cleaning teeth' },
  { normal: 'Taking a shower', secret: 'Getting clean' },
  { normal: 'Walking a dog', secret: 'Walking a pet' },
  { normal: 'Playing catch', secret: 'Throwing a ball' },
  { normal: 'Hugging', secret: 'Embracing' },
  { normal: 'Waving hello', secret: 'Greeting someone' },
  { normal: 'Pointing', secret: 'Gesturing' },
  { normal: 'Clapping', secret: 'Applauding' },
  { normal: 'Sneezing', secret: 'Blowing your nose' },
  { normal: 'Yawning', secret: 'Being tired' },
  { normal: 'Crying', secret: 'Being very sad' },
  { normal: 'Laughing', secret: 'Smiling big' },
  { normal: 'Thinking', secret: 'Wondering' },
  { normal: 'Singing', secret: 'Performing' },

  // Emotions & Expressions
  { normal: 'A happy person', secret: 'A cheerful person' },
  { normal: 'A sad person', secret: 'An upset person' },
  { normal: 'An angry person', secret: 'A frustrated person' },
  { normal: 'A scared person', secret: 'A worried person' },
  { normal: 'A surprised person', secret: 'A shocked person' },
  { normal: 'Someone confused', secret: 'Someone puzzled' },
  { normal: 'Someone excited', secret: 'Someone energetic' },
  { normal: 'Someone tired', secret: 'Someone sleepy' },
  { normal: 'Someone embarrassed', secret: 'Someone shy' },
  { normal: 'Someone proud', secret: 'Someone confident' },

  // Animals doing things
  { normal: 'A cat sleeping', secret: 'A cat resting' },
  { normal: 'A dog playing', secret: 'A dog running' },
  { normal: 'A bird flying', secret: 'A bird with wings out' },
  { normal: 'A fish swimming', secret: 'A fish in water' },
  { normal: 'A monkey climbing', secret: 'A monkey in a tree' },
  { normal: 'An elephant spraying water', secret: 'An elephant with its trunk up' },
  { normal: 'A penguin sliding', secret: 'A kid sliding' },
  { normal: 'A snake slithering', secret: 'A snake moving' },
  { normal: 'A bear waving', secret: 'A bear standing' },
  { normal: 'A frog jumping', secret: 'A frog hopping' },

  // Situations & Scenes
  { normal: 'A birthday party', secret: 'A celebration' },
  { normal: 'A picnic', secret: 'Eating outside' },
  { normal: 'A camping trip', secret: 'A vacation' },
  { normal: 'A beach day', secret: 'At the ocean' },
  { normal: 'A rainy day', secret: 'Bad weather' },
  { normal: 'A snowy day', secret: 'Cold weather' },
  { normal: 'Sunset', secret: 'Evening sky' },
  { normal: 'Sunrise', secret: 'Morning sky' },
  { normal: 'A rainbow', secret: 'Colorful arc' },
  { normal: 'Fireworks', secret: 'Explosions in the sky' },
  { normal: 'A concert', secret: 'A performance' },
  { normal: 'A wedding', secret: 'A ceremony' },
  { normal: 'A graduation', secret: 'A ceremony' },
  { normal: 'A snowman', secret: 'A snow sculpture' },
  { normal: 'Building a sandcastle', secret: 'Building a castle' },
  { normal: 'Flying a kite', secret: 'Something flying' },
  { normal: 'A bonfire', secret: 'A big fire' },
  { normal: 'Stargazing', secret: 'Looking at the sky' },

  // Sports & Games
  { normal: 'Playing basketball', secret: 'Shooting hoops' },
  { normal: 'Playing soccer', secret: 'Kicking a ball' },
  { normal: 'Playing baseball', secret: 'Hitting a ball' },
  { normal: 'Playing tennis', secret: 'Using a racket' },
  { normal: 'Playing golf', secret: 'Hitting a small ball' },
  { normal: 'Playing football', secret: 'Throwing a ball' },
  { normal: 'Bowling', secret: 'Rolling a ball' },
  { normal: 'Ice skating', secret: 'Skating' },
  { normal: 'Skiing', secret: 'Going down a slope' },
  { normal: 'Surfing', secret: 'Riding a wave' },
  { normal: 'Rock climbing', secret: 'Climbing' },
  { normal: 'Skateboarding', secret: 'Riding a board' },
  { normal: 'Rollerblading', secret: 'Skating' },
  { normal: 'Hopscotch', secret: 'A hopping game' },
  { normal: 'Jump rope', secret: 'Jumping' },
  { normal: 'Tug of war', secret: 'Pulling a rope' },

  // Jobs & Professions
  { normal: 'A doctor', secret: 'A medical person' },
  { normal: 'A teacher', secret: 'Someone at a chalkboard' },
  { normal: 'A firefighter', secret: 'An emergency worker' },
  { normal: 'A police officer', secret: 'A security guard' },
  { normal: 'A chef', secret: 'A cook' },
  { normal: 'An astronaut', secret: 'A space person' },
  { normal: 'A pilot', secret: 'Someone flying' },
  { normal: 'A dentist', secret: 'A teeth doctor' },
  { normal: 'A musician', secret: 'A performer' },
  { normal: 'A painter', secret: 'An artist' },
  { normal: 'A construction worker', secret: 'A builder' },
  { normal: 'A mail carrier', secret: 'A delivery person' },
  { normal: 'A farmer', secret: 'Someone with crops' },

  // Objects in use
  { normal: 'An umbrella in the rain', secret: 'Protection from rain' },
  { normal: 'A balloon floating', secret: 'Something floating' },
  { normal: 'A kite flying', secret: 'Something in the wind' },
  { normal: 'A campfire', secret: 'An outdoor fire' },
  { normal: 'A birthday cake', secret: 'A cake with candles' },
  { normal: 'An ice cream cone melting', secret: 'A melting treat' },
  { normal: 'A broken window', secret: 'A cracked window' },
  { normal: 'A ringing phone', secret: 'A phone' },
  { normal: 'A television', secret: 'A screen' },
  { normal: 'A computer', secret: 'A laptop' },
  { normal: 'Headphones', secret: 'Earbuds' },
  { normal: 'A camera', secret: 'Taking pictures' },
  { normal: 'Sunglasses', secret: 'Glasses' },
  { normal: 'A backpack', secret: 'A bag' },

  // Nature & Weather
  { normal: 'A tree', secret: 'A plant' },
  { normal: 'A flower', secret: 'A plant with petals' },
  { normal: 'Mountains', secret: 'Hills' },
  { normal: 'The ocean', secret: 'A big body of water' },
  { normal: 'A river', secret: 'Flowing water' },
  { normal: 'A waterfall', secret: 'Water falling' },
  { normal: 'Lightning', secret: 'A storm' },
  { normal: 'A tornado', secret: 'A spiral wind' },
  { normal: 'Clouds', secret: 'The sky' },
  { normal: 'The sun', secret: 'A giant circle' },
  { normal: 'The moon', secret: 'A crescent' },
  { normal: 'Stars', secret: 'Night sky' },
  { normal: 'A cactus', secret: 'A desert plant' },

  // Food & Meals
  { normal: 'Eating pizza', secret: 'Eating a slice' },
  { normal: 'A hamburger', secret: 'A burger' },
  { normal: 'A hot dog', secret: 'A sausage' },
  { normal: 'Ice cream', secret: 'A frozen treat' },
  { normal: 'A birthday cake', secret: 'A decorated cake' },
  { normal: 'Spaghetti', secret: 'Noodles' },
  { normal: 'A sandwich', secret: 'Bread with filling' },
  { normal: 'Popcorn', secret: 'A movie snack' },
  { normal: 'French fries', secret: 'Fried potatoes' },
  { normal: 'A taco', secret: 'A folded food' },
  { normal: 'Breakfast', secret: 'Morning meal' },
  { normal: 'Dinner time', secret: 'Evening meal' },

  // Transportation
  { normal: 'A car', secret: 'A vehicle' },
  { normal: 'A bicycle', secret: 'A bike' },
  { normal: 'An airplane', secret: 'A flying vehicle' },
  { normal: 'A boat', secret: 'A water vehicle' },
  { normal: 'A train', secret: 'A long vehicle' },
  { normal: 'A helicopter', secret: 'A flying machine' },
  { normal: 'A rocket', secret: 'A space ship' },
  { normal: 'A motorcycle', secret: 'A two-wheeled vehicle' },
  { normal: 'A school bus', secret: 'A yellow bus' },
  { normal: 'A fire truck', secret: 'An emergency vehicle' },

  // Buildings & Places
  { normal: 'A house', secret: 'A home' },
  { normal: 'A school', secret: 'A building' },
  { normal: 'A hospital', secret: 'A medical building' },
  { normal: 'A castle', secret: 'A fortress' },
  { normal: 'A lighthouse', secret: 'A tall tower' },
  { normal: 'A church', secret: 'A building with a cross' },
  { normal: 'A barn', secret: 'A farm building' },
  { normal: 'The Eiffel Tower', secret: 'A famous tower' },
  { normal: 'A pyramid', secret: 'A triangle building' },
  { normal: 'A bridge', secret: 'A crossing' },

  // Household Items
  { normal: 'A chair', secret: 'A seat' },
  { normal: 'A table', secret: 'A flat surface' },
  { normal: 'A bed', secret: 'A place to sleep' },
  { normal: 'A lamp', secret: 'A light' },
  { normal: 'A clock', secret: 'Showing time' },
  { normal: 'A mirror', secret: 'A reflection' },
  { normal: 'A picture frame', secret: 'A frame' },
  { normal: 'A door', secret: 'An entrance' },
  { normal: 'A window', secret: 'An opening' },
  { normal: 'Stairs', secret: 'Steps' },

  // Miscellaneous
  { normal: 'A ghost', secret: 'A floating spirit' },
  { normal: 'A robot', secret: 'A machine' },
  { normal: 'A superhero', secret: 'A police man' },
  { normal: 'A princess', secret: 'A queen' },
  { normal: 'A king', secret: 'A ruler' },
  { normal: 'A pirate', secret: 'A sailor' },
  { normal: 'A cowboy', secret: 'A rancher' },
  { normal: 'A dinosaur', secret: 'A big lizard' },
  { normal: 'A dragon', secret: 'A flying creature' },
  { normal: 'An alien', secret: 'A strange creature' },
  { normal: 'A monster', secret: 'A scary creature' },
  { normal: 'A wizard', secret: 'A magician' },
  { normal: 'A mermaid', secret: 'A person in water' },
  { normal: 'A unicorn', secret: 'A horse' },

  // More Activities
  { normal: 'Fishing', secret: 'Waiting with a pole' },
  { normal: 'Gardening', secret: 'Planting' },
  { normal: 'Jogging', secret: 'Exercise' },
  { normal: 'Yoga', secret: 'Stretching' },
  { normal: 'Meditating', secret: 'Sitting quietly' },
  { normal: 'Praying', secret: 'Kneeling' },
  { normal: 'Hiking', secret: 'Walking uphill' },
  { normal: 'Climbing stairs', secret: 'Going up steps' },
  { normal: 'Opening a door', secret: 'Pulling a handle' },
  { normal: 'Closing a window', secret: 'Shutting something' },
  { normal: 'Knocking', secret: 'Hitting a door' },
  { normal: 'Ringing a doorbell', secret: 'Pressing a button' },
  { normal: 'Sweeping', secret: 'Cleaning the floor' },
  { normal: 'Mopping', secret: 'Washing the floor' },
  { normal: 'Vacuuming', secret: 'Cleaning carpet' },
  { normal: 'Dusting', secret: 'Wiping surfaces' },
  { normal: 'Doing laundry', secret: 'Washing clothes' },
  { normal: 'Folding clothes', secret: 'Organizing laundry' },
  { normal: 'Ironing', secret: 'Smoothing clothes' },
  { normal: 'Sewing', secret: 'Using needle and thread' },
  { normal: 'Knitting', secret: 'Using yarn' },
  { normal: 'Playing chess', secret: 'A board game' },
  { normal: 'Playing cards', secret: 'A card game' },
  { normal: 'Playing checkers', secret: 'A game with pieces' },
  { normal: 'Building with blocks', secret: 'Stacking things' },
  { normal: 'Playing with a yo-yo', secret: 'A toy on a string' },
  { normal: 'Flying a drone', secret: 'Controlling something flying' },
  { normal: 'Taking a nap', secret: 'Resting' },
  { normal: 'Stretching', secret: 'Reaching' },
  { normal: 'Exercising', secret: 'Working out' },
  { normal: 'Doing push-ups', secret: 'Exercise on the floor' },
  { normal: 'Doing sit-ups', secret: 'Crunches' },
  { normal: 'Lifting weights', secret: 'Holding heavy objects' },

  // More Emotions & States
  { normal: 'Someone bored', secret: 'Someone uninterested' },
  { normal: 'Someone sick', secret: 'Someone not feeling well' },
  { normal: 'Someone cold', secret: 'Someone shivering' },
  { normal: 'Someone hot', secret: 'Someone sweating' },
  { normal: 'Someone thirsty', secret: 'Someone needing water' },
  { normal: 'Someone hungry', secret: 'Someone wanting food' },
  { normal: 'Someone sleepy', secret: 'Someone drowsy' },
  { normal: 'Someone awake', secret: 'Someone alert' },
  { normal: 'Someone jealous', secret: 'Someone envious' },
  { normal: 'Someone guilty', secret: 'Someone regretful' },
  { normal: 'Someone relieved', secret: 'Someone relaxed' },
  { normal: 'Someone nervous', secret: 'Someone anxious' },
  { normal: 'Someone confident', secret: 'Someone sure' },
  { normal: 'Someone lonely', secret: 'Someone alone' },

  // More Animals & Creatures
  { normal: 'A horse running', secret: 'A horse galloping' },
  { normal: 'A bird eating', secret: 'A bird pecking' },
  { normal: 'A bee buzzing', secret: 'An insect flying' },
  { normal: 'An ant carrying food', secret: 'A small bug working' },
  { normal: 'A spider on a web', secret: 'A bug on strings' },
  { normal: 'A butterfly on a flower', secret: 'An insect on a plant' },
  { normal: 'A squirrel eating nuts', secret: 'A small animal eating' },
  { normal: 'A rabbit hopping', secret: 'A bunny jumping' },
  { normal: 'A deer in the forest', secret: 'An animal in the woods' },
  { normal: 'A wolf howling', secret: 'A dog making noise' },
  { normal: 'A lion roaring', secret: 'A big cat making noise' },
  { normal: 'A mouse running', secret: 'A small creature scurrying' },
  { normal: 'A bat flying', secret: 'A winged creature at night' },
  { normal: 'An owl in a tree', secret: 'A bird at night' },
  { normal: 'A peacock showing feathers', secret: 'A colorful bird' },
  { normal: 'A kangaroo jumping', secret: 'An animal bouncing' },
  { normal: 'A koala sleeping', secret: 'An animal in a tree' },
  { normal: 'A panda eating bamboo', secret: 'A bear eating' },
  { normal: 'A seal clapping', secret: 'An animal making noise' },
  { normal: 'A walrus on ice', secret: 'A large sea animal' },

  // More Situations & Scenes
  { normal: 'A parade', secret: 'A procession' },
  { normal: 'A circus', secret: 'A show with performers' },
  { normal: 'A fair', secret: 'A carnival' },
  { normal: 'A festival', secret: 'A celebration' },
  { normal: 'A market', secret: 'People selling things' },
  { normal: 'A garage sale', secret: 'Selling used items' },
  { normal: 'A barbecue', secret: 'Outdoor cooking' },
  { normal: 'A potluck', secret: 'A shared meal' },
  { normal: 'A family reunion', secret: 'A gathering' },
  { normal: 'A sleepover', secret: 'Staying overnight' },
  { normal: 'A movie theater', secret: 'Watching a film' },
  { normal: 'An amusement park', secret: 'A place with rides' },
  { normal: 'A zoo', secret: 'A place with animals' },
  { normal: 'An aquarium', secret: 'A place with fish' },
  { normal: 'A museum', secret: 'A place with exhibits' },
  { normal: 'A library', secret: 'A place with books' },
  { normal: 'A restaurant', secret: 'A place to eat' },
  { normal: 'A coffee shop', secret: 'A cafe' },
  { normal: 'A bakery', secret: 'A place with bread' },
  { normal: 'A grocery store', secret: 'A food store' },
  { normal: 'A gas station', secret: 'A fuel station' },
  { normal: 'A car wash', secret: 'Cleaning a vehicle' },
  { normal: 'A traffic jam', secret: 'Many stopped cars' },
  { normal: 'An intersection', secret: 'Where roads meet' },
  { normal: 'A parking lot', secret: 'A place for cars' },
  { normal: 'A playground', secret: 'A place for kids' },
  { normal: 'A skate park', secret: 'A place with ramps' },

  // More Weather & Nature
  { normal: 'A thunderstorm', secret: 'Heavy rain' },
  { normal: 'A blizzard', secret: 'Heavy snow' },
  { normal: 'A hurricane', secret: 'Strong wind and rain' },
  { normal: 'An earthquake', secret: 'Shaking ground' },
  { normal: 'A volcano erupting', secret: 'Mountain exploding' },
  { normal: 'A forest fire', secret: 'Trees burning' },
  { normal: 'A flood', secret: 'Too much water' },
  { normal: 'A drought', secret: 'No rain' },
  { normal: 'Fog', secret: 'Cloudy air' },
  { normal: 'Dew on grass', secret: 'Wet grass' },
  { normal: 'Frost on windows', secret: 'Ice on glass' },
  { normal: 'Icicles', secret: 'Ice hanging' },
  { normal: 'A puddle', secret: 'Water on ground' },
  { normal: 'Mud', secret: 'Wet dirt' },
  { normal: 'A desert', secret: 'Sandy place' },
  { normal: 'A jungle', secret: 'Dense forest' },
  { normal: 'A meadow', secret: 'Grassy field' },
  { normal: 'A valley', secret: 'Low area between hills' },
  { normal: 'A cave', secret: 'A hole in rock' },
  { normal: 'A cliff', secret: 'A steep drop' },
  { normal: 'A beach', secret: 'Sand by water' },
  { normal: 'An island', secret: 'Land surrounded by water' },
  { normal: 'A pond', secret: 'Small body of water' },
  { normal: 'A stream', secret: 'Small river' },
  { normal: 'A swamp', secret: 'Wetland' },

  // More Food & Drinks
  { normal: 'A cupcake', secret: 'A small cake' },
  { normal: 'A muffin', secret: 'A breakfast pastry' },
  { normal: 'Pancakes', secret: 'Flat breakfast food' },
  { normal: 'Waffles', secret: 'Grid breakfast food' },
  { normal: 'Toast', secret: 'Toasted bread' },
  { normal: 'Cereal', secret: 'Breakfast in a bowl' },
  { normal: 'Bacon', secret: 'Crispy meat strips' },
  { normal: 'Eggs', secret: 'Breakfast protein' },
  { normal: 'Salad', secret: 'Mixed vegetables' },
  { normal: 'Soup', secret: 'Hot liquid food' },
  { normal: 'Stew', secret: 'Thick soup' },
  { normal: 'Chili', secret: 'Spicy dish' },
  { normal: 'Nachos', secret: 'Chips with toppings' },
  { normal: 'Burrito', secret: 'Wrapped food' },
  { normal: 'Quesadilla', secret: 'Folded tortilla' },
  { normal: 'Sushi', secret: 'Raw fish rolls' },
  { normal: 'Ramen', secret: 'Noodle soup' },
  { normal: 'Dumplings', secret: 'Filled dough' },
  { normal: 'Spring rolls', secret: 'Wrapped appetizer' },
  { normal: 'Fried chicken', secret: 'Crispy poultry' },
  { normal: 'BBQ ribs', secret: 'Grilled meat' },
  { normal: 'Steak', secret: 'Grilled beef' },
  { normal: 'Lobster', secret: 'Fancy seafood' },
  { normal: 'Shrimp', secret: 'Small seafood' },
  { normal: 'Oysters', secret: 'Shellfish' },
  { normal: 'Caviar', secret: 'Fish eggs' },
  { normal: 'Cheese', secret: 'Dairy product' },
  { normal: 'Yogurt', secret: 'Creamy dairy' },
  { normal: 'Smoothie', secret: 'Blended drink' },
  { normal: 'Milkshake', secret: 'Thick sweet drink' },
  { normal: 'Hot chocolate', secret: 'Warm sweet drink' },
  { normal: 'Lemonade', secret: 'Citrus drink' },
  { normal: 'Juice', secret: 'Fruit drink' },
  { normal: 'Wine', secret: 'Grape beverage' },
  { normal: 'Beer', secret: 'Fizzy beverage' },

  // Technology & Modern Items
  { normal: 'A smartphone', secret: 'A mobile device' },
  { normal: 'A tablet', secret: 'A flat computer' },
  { normal: 'A laptop', secret: 'A portable computer' },
  { normal: 'A keyboard', secret: 'Typing device' },
  { normal: 'A mouse', secret: 'Computer pointer' },
  { normal: 'A printer', secret: 'Paper machine' },
  { normal: 'A scanner', secret: 'Copy machine' },
  { normal: 'A webcam', secret: 'Video camera' },
  { normal: 'A microphone', secret: 'Sound recorder' },
  { normal: 'A USB drive', secret: 'Storage device' },
  { normal: 'Charging a phone', secret: 'Plugging in device' },
  { normal: 'Typing on keyboard', secret: 'Using fingers on buttons' },
  { normal: 'Clicking a mouse', secret: 'Pressing a button' },
  { normal: 'Scrolling', secret: 'Moving through content' },
  { normal: 'Taking a screenshot', secret: 'Capturing the screen' },
  { normal: 'Video calling', secret: 'Talking on screen' },
  { normal: 'Sending a text', secret: 'Typing a message' },
  { normal: 'Posting on social media', secret: 'Sharing online' },
  { normal: 'Taking a video', secret: 'Recording' },
  { normal: 'Editing a photo', secret: 'Changing a picture' },

  // Musical & Performance
  { normal: 'Playing drums', secret: 'Hitting percussion' },
  { normal: 'Playing guitar', secret: 'Strumming strings' },
  { normal: 'Playing piano', secret: 'Pressing keys' },
  { normal: 'Playing violin', secret: 'Using a bow' },
  { normal: 'Playing trumpet', secret: 'Blowing brass' },
  { normal: 'Playing flute', secret: 'Blowing woodwind' },
  { normal: 'Conducting an orchestra', secret: 'Leading musicians' },
  { normal: 'Singing in a choir', secret: 'Group singing' },
  { normal: 'Playing harmonica', secret: 'Blowing small instrument' },
  { normal: 'Playing accordion', secret: 'Squeezing instrument' },
  { normal: 'DJing', secret: 'Playing music' },
  { normal: 'Breakdancing', secret: 'Floor dancing' },
  { normal: 'Ballet', secret: 'Classical dance' },
  { normal: 'Tap dancing', secret: 'Dancing with sound' },
  { normal: 'Juggling', secret: 'Tossing objects' },
  { normal: 'Magic trick', secret: 'Illusion' },
  { normal: 'Mime', secret: 'Silent performance' },
  { normal: 'Acrobatics', secret: 'Flipping and tumbling' },
  { normal: 'Tightrope walking', secret: 'Balancing on rope' },
  { normal: 'Fire breathing', secret: 'Dangerous performance' },

  // Holidays & Celebrations
  { normal: 'Blowing out birthday candles', secret: 'Putting out small flames' },
  { normal: 'Opening gifts', secret: 'Unwrapping presents' },
  { normal: 'Wrapping presents', secret: 'Covering gifts' },
  { normal: 'New Year countdown', secret: 'Counting down' },
  { normal: 'Fireworks display', secret: 'Sky explosions' },
  { normal: 'Easter egg hunt', secret: 'Searching for eggs' },
  { normal: 'Dyeing Easter eggs', secret: 'Coloring eggs' },
  { normal: 'Thanksgiving dinner', secret: 'Big family meal' },
  { normal: 'Carving turkey', secret: 'Cutting meat' },
  { normal: 'Valentine card', secret: 'Love note' },
  { normal: 'Fourth of July', secret: 'Summer celebration' },
];

// Story prompts for Story Remix
export const storyPrompts = [
  'Once upon a time in a magical kingdom...',
  'It was a dark and stormy night when suddenly...',
  'In the year 2525, humans discovered...',
  'The detective knew something was wrong when...',
  'Nobody expected what would happen at the party...',
  'The treasure map led them to...',
  'On the first day of school, they found...',
  'The secret door in the basement opened to reveal...',
  'When the clock struck midnight...',
  'The last thing they remembered was...',
];

// Story twist prompts
export const storyTwists = [
  'Add a character who is actually a time traveler',
  'Introduce a magical object that changes everything',
  'Make something explode (but everyone is okay)',
  'Add an unexpected animal character',
  'Reveal that it was all a dream... or was it?',
  'Introduce a villain with a silly weakness',
  'Add a dance party',
  'Make someone discover they have superpowers',
  'Add a mysterious stranger with important news',
  'Include a chase scene',
];

// Fact or Fiction question categories
export const factCategories = [
  'Tell us about an embarrassing moment',
  'Share an unusual talent or skill you have',
  'Describe a strange food you\'ve eaten',
  'Tell us about a weird dream you remember',
  'Share an interesting place you\'ve visited',
  'Describe something you\'re afraid of',
  'Tell us about a time you got lost',
  'Share a hidden talent',
  'Describe your most unusual pet or animal encounter',
  'Tell us about a time you broke something',
];

// Mission Mayhem mission descriptions
export const missions = [
  'Explore the Ancient Temple',
  'Hack the Mainframe',
  'Retrieve the Secret Documents',
  'Disable the Security System',
  'Rescue the Hostage',
  'Plant the Tracking Device',
  'Steal the Rare Artifact',
  'Decode the Message',
  'Sabotage the Enemy Base',
  'Escape the Facility',
];
