// Drawing prompts for Secret Artist - Easy to identify, hard to draw well
// Each prompt has a normal version and a secret artist version (similar but different)
export const drawingPrompts = [
  // Actions & Activities
  { normal: 'Someone sleeping', secret: 'Someone resting' },
  { normal: 'Running', secret: 'Jogging' },
  { normal: 'Swimming', secret: 'Floating in water' },
  { normal: 'Dancing', secret: 'Moving to music' },
  { normal: 'Jumping', secret: 'Hopping' },
  { normal: 'Eating', secret: 'Having a snack' },
  { normal: 'Drinking', secret: 'Having a beverage' },
  { normal: 'Reading a book', secret: 'Looking at a magazine' },
  { normal: 'Watching TV', secret: 'Looking at a screen' },
  { normal: 'Playing video games', secret: 'Using a controller' },
  { normal: 'Texting on a phone', secret: 'Using a phone' },
  { normal: 'Taking a selfie', secret: 'Taking a photo' },
  { normal: 'Cooking', secret: 'Making food' },
  { normal: 'Driving a car', secret: 'Steering a vehicle' },
  { normal: 'Riding a bike', secret: 'Pedaling' },
  { normal: 'Skateboarding', secret: 'Riding a board' },
  { normal: 'Brushing teeth', secret: 'Cleaning teeth' },
  { normal: 'Taking a shower', secret: 'Getting clean' },
  { normal: 'Walking a dog', secret: 'Walking a pet' },
  { normal: 'Playing catch', secret: 'Throwing a ball' },
  { normal: 'Hugging', secret: 'Embracing' },
  { normal: 'Waving hello', secret: 'Greeting someone' },
  { normal: 'Pointing', secret: 'Gesturing' },
  { normal: 'Clapping', secret: 'Applauding' },
  { normal: 'Sneezing', secret: 'Blowing your nose' },
  { normal: 'Yawning', secret: 'Being tired' },
  { normal: 'Crying', secret: 'Being very sad' },
  { normal: 'Laughing', secret: 'Smiling big' },
  { normal: 'Thinking', secret: 'Wondering' },
  { normal: 'Singing', secret: 'Performing' },

  // Emotions & Expressions
  { normal: 'A happy person', secret: 'A cheerful person' },
  { normal: 'A sad person', secret: 'An upset person' },
  { normal: 'An angry person', secret: 'A frustrated person' },
  { normal: 'A scared person', secret: 'A worried person' },
  { normal: 'A surprised person', secret: 'A shocked person' },
  { normal: 'Someone confused', secret: 'Someone puzzled' },
  { normal: 'Someone excited', secret: 'Someone energetic' },
  { normal: 'Someone tired', secret: 'Someone sleepy' },
  { normal: 'Someone embarrassed', secret: 'Someone shy' },
  { normal: 'Someone proud', secret: 'Someone confident' },

  // Animals doing things
  { normal: 'A cat sleeping', secret: 'A cat resting' },
  { normal: 'A dog playing', secret: 'A dog running' },
  { normal: 'A bird flying', secret: 'A bird with wings out' },
  { normal: 'A fish swimming', secret: 'A fish in water' },
  { normal: 'A monkey climbing', secret: 'A monkey in a tree' },
  { normal: 'An elephant spraying water', secret: 'An elephant with its trunk up' },
  { normal: 'A penguin sliding', secret: 'A kid sliding' },
  { normal: 'A snake slithering', secret: 'A snake moving' },
  { normal: 'A bear waving', secret: 'A bear standing' },
  { normal: 'A frog jumping', secret: 'A frog hopping' },

  // Situations & Scenes
  { normal: 'A birthday party', secret: 'A celebration' },
  { normal: 'A picnic', secret: 'Eating outside' },
  { normal: 'A camping trip', secret: 'A vacation' },
  { normal: 'A beach day', secret: 'At the ocean' },
  { normal: 'A rainy day', secret: 'Bad weather' },
  { normal: 'A snowy day', secret: 'Cold weather' },
  { normal: 'Sunset', secret: 'Evening sky' },
  { normal: 'Sunrise', secret: 'Morning sky' },
  { normal: 'A rainbow', secret: 'Colorful arc' },
  { normal: 'Fireworks', secret: 'Explosions in the sky' },
  { normal: 'A concert', secret: 'A performance' },
  { normal: 'A wedding', secret: 'A ceremony' },
  { normal: 'A graduation', secret: 'A ceremony' },
  { normal: 'Halloween', secret: 'A costume party' },
  { normal: 'Christmas morning', secret: 'Opening presents' },
  { normal: 'A snowman', secret: 'A snow sculpture' },
  { normal: 'Building a sandcastle', secret: 'Building a castle' },
  { normal: 'Flying a kite', secret: 'Something flying' },
  { normal: 'A bonfire', secret: 'A big fire' },
  { normal: 'Stargazing', secret: 'Looking at the sky' },

  // Sports & Games
  { normal: 'Playing basketball', secret: 'Shooting hoops' },
  { normal: 'Playing soccer', secret: 'Kicking a ball' },
  { normal: 'Playing baseball', secret: 'Hitting a ball' },
  { normal: 'Playing tennis', secret: 'Using a racket' },
  { normal: 'Playing golf', secret: 'Hitting a small ball' },
  { normal: 'Playing football', secret: 'Throwing a ball' },
  { normal: 'Bowling', secret: 'Rolling a ball' },
  { normal: 'Ice skating', secret: 'Skating' },
  { normal: 'Skiing', secret: 'Going down a slope' },
  { normal: 'Surfing', secret: 'Riding a wave' },
  { normal: 'Rock climbing', secret: 'Climbing' },
  { normal: 'Skateboarding', secret: 'Riding a board' },
  { normal: 'Rollerblading', secret: 'Skating' },
  { normal: 'Hopscotch', secret: 'A hopping game' },
  { normal: 'Jump rope', secret: 'Jumping' },
  { normal: 'Tug of war', secret: 'Pulling a rope' },

  // Jobs & Professions
  { normal: 'A doctor', secret: 'A medical person' },
  { normal: 'A teacher', secret: 'Someone at a chalkboard' },
  { normal: 'A firefighter', secret: 'An emergency worker' },
  { normal: 'A police officer', secret: 'A security guard' },
  { normal: 'A chef', secret: 'A cook' },
  { normal: 'An astronaut', secret: 'A space person' },
  { normal: 'A pilot', secret: 'Someone flying' },
  { normal: 'A dentist', secret: 'A teeth doctor' },
  { normal: 'A musician', secret: 'A performer' },
  { normal: 'A painter', secret: 'An artist' },
  { normal: 'A construction worker', secret: 'A builder' },
  { normal: 'A mail carrier', secret: 'A delivery person' },
  { normal: 'A farmer', secret: 'Someone with crops' },

  // Objects in use
  { normal: 'An umbrella in the rain', secret: 'Protection from rain' },
  { normal: 'A balloon floating', secret: 'Something floating' },
  { normal: 'A kite flying', secret: 'Something in the wind' },
  { normal: 'A campfire', secret: 'An outdoor fire' },
  { normal: 'A birthday cake', secret: 'A cake with candles' },
  { normal: 'An ice cream cone melting', secret: 'A melting treat' },
  { normal: 'A broken window', secret: 'A cracked window' },
  { normal: 'A ringing phone', secret: 'A phone' },
  { normal: 'A television', secret: 'A screen' },
  { normal: 'A computer', secret: 'A laptop' },
  { normal: 'Headphones', secret: 'Earbuds' },
  { normal: 'A camera', secret: 'Taking pictures' },
  { normal: 'Sunglasses', secret: 'Glasses' },
  { normal: 'A backpack', secret: 'A bag' },

  // Nature & Weather
  { normal: 'A tree', secret: 'A plant' },
  { normal: 'A flower', secret: 'A plant with petals' },
  { normal: 'Mountains', secret: 'Hills' },
  { normal: 'The ocean', secret: 'A big body of water' },
  { normal: 'A river', secret: 'Flowing water' },
  { normal: 'A waterfall', secret: 'Water falling' },
  { normal: 'Lightning', secret: 'A storm' },
  { normal: 'A tornado', secret: 'A spiral wind' },
  { normal: 'Clouds', secret: 'The sky' },
  { normal: 'The sun', secret: 'A giant circle' },
  { normal: 'The moon', secret: 'A crescent' },
  { normal: 'Stars', secret: 'Night sky' },
  { normal: 'A cactus', secret: 'A desert plant' },

  // Food & Meals
  { normal: 'Eating pizza', secret: 'Eating a slice' },
  { normal: 'A hamburger', secret: 'A burger' },
  { normal: 'A hot dog', secret: 'A sausage' },
  { normal: 'Ice cream', secret: 'A frozen treat' },
  { normal: 'A birthday cake', secret: 'A decorated cake' },
  { normal: 'Spaghetti', secret: 'Noodles' },
  { normal: 'A sandwich', secret: 'Bread with filling' },
  { normal: 'Popcorn', secret: 'A movie snack' },
  { normal: 'French fries', secret: 'Fried potatoes' },
  { normal: 'A taco', secret: 'A folded food' },
  { normal: 'Breakfast', secret: 'Morning meal' },
  { normal: 'Dinner time', secret: 'Evening meal' },

  // Transportation
  { normal: 'A car', secret: 'A vehicle' },
  { normal: 'A bicycle', secret: 'A bike' },
  { normal: 'An airplane', secret: 'A flying vehicle' },
  { normal: 'A boat', secret: 'A water vehicle' },
  { normal: 'A train', secret: 'A long vehicle' },
  { normal: 'A helicopter', secret: 'A flying machine' },
  { normal: 'A rocket', secret: 'A space ship' },
  { normal: 'A motorcycle', secret: 'A two-wheeled vehicle' },
  { normal: 'A school bus', secret: 'A yellow bus' },
  { normal: 'A fire truck', secret: 'An emergency vehicle' },

  // Buildings & Places
  { normal: 'A house', secret: 'A home' },
  { normal: 'A school', secret: 'A building' },
  { normal: 'A hospital', secret: 'A medical building' },
  { normal: 'A castle', secret: 'A fortress' },
  { normal: 'A lighthouse', secret: 'A tall tower' },
  { normal: 'A church', secret: 'A building with a cross' },
  { normal: 'A barn', secret: 'A farm building' },
  { normal: 'The Eiffel Tower', secret: 'A famous tower' },
  { normal: 'A pyramid', secret: 'A triangle building' },
  { normal: 'A bridge', secret: 'A crossing' },

  // Household Items
  { normal: 'A chair', secret: 'A seat' },
  { normal: 'A table', secret: 'A flat surface' },
  { normal: 'A bed', secret: 'A place to sleep' },
  { normal: 'A lamp', secret: 'A light' },
  { normal: 'A clock', secret: 'Showing time' },
  { normal: 'A mirror', secret: 'A reflection' },
  { normal: 'A picture frame', secret: 'A frame' },
  { normal: 'A door', secret: 'An entrance' },
  { normal: 'A window', secret: 'An opening' },
  { normal: 'Stairs', secret: 'Steps' },

  // Miscellaneous
  { normal: 'A ghost', secret: 'A floating spirit' },
  { normal: 'A robot', secret: 'A machine' },
  { normal: 'A superhero', secret: 'A police man' },
  { normal: 'A princess', secret: 'A queen' },
  { normal: 'A king', secret: 'A ruler' },
  { normal: 'A pirate', secret: 'A sailor' },
  { normal: 'A cowboy', secret: 'A rancher' },
  { normal: 'A dinosaur', secret: 'A big lizard' },
  { normal: 'A dragon', secret: 'A flying creature' },
  { normal: 'An alien', secret: 'A strange creature' },
  { normal: 'A monster', secret: 'A scary creature' },
  { normal: 'A wizard', secret: 'A magician' },
  { normal: 'A mermaid', secret: 'A person in water' },
  { normal: 'A unicorn', secret: 'A horse' },
];

// Story prompts for Story Remix
export const storyPrompts = [
  'Once upon a time in a magical kingdom...',
  'It was a dark and stormy night when suddenly...',
  'In the year 2525, humans discovered...',
  'The detective knew something was wrong when...',
  'Nobody expected what would happen at the party...',
  'The treasure map led them to...',
  'On the first day of school, they found...',
  'The secret door in the basement opened to reveal...',
  'When the clock struck midnight...',
  'The last thing they remembered was...',
];

// Story twist prompts
export const storyTwists = [
  'Add a character who is actually a time traveler',
  'Introduce a magical object that changes everything',
  'Make something explode (but everyone is okay)',
  'Add an unexpected animal character',
  'Reveal that it was all a dream... or was it?',
  'Introduce a villain with a silly weakness',
  'Add a dance party',
  'Make someone discover they have superpowers',
  'Add a mysterious stranger with important news',
  'Include a chase scene',
];

// Fact or Fiction question categories
export const factCategories = [
  'Tell us about an embarrassing moment',
  'Share an unusual talent or skill you have',
  'Describe a strange food you\'ve eaten',
  'Tell us about a weird dream you remember',
  'Share an interesting place you\'ve visited',
  'Describe something you\'re afraid of',
  'Tell us about a time you got lost',
  'Share a hidden talent',
  'Describe your most unusual pet or animal encounter',
  'Tell us about a time you broke something',
];

// Mission Mayhem mission descriptions
export const missions = [
  'Explore the Ancient Temple',
  'Hack the Mainframe',
  'Retrieve the Secret Documents',
  'Disable the Security System',
  'Rescue the Hostage',
  'Plant the Tracking Device',
  'Steal the Rare Artifact',
  'Decode the Message',
  'Sabotage the Enemy Base',
  'Escape the Facility',
];
