// Drawing prompts for Secret Artist - Easy to identify, hard to draw well
export const drawingPrompts = [
  // Actions & Activities
  'Someone sleeping',
  'Running',
  'Swimming',
  'Dancing',
  'Jumping',
  'Eating',
  'Drinking',
  'Reading a book',
  'Watching TV',
  'Playing video games',
  'Texting on a phone',
  'Taking a selfie',
  'Cooking',
  'Driving a car',
  'Riding a bike',
  'Skateboarding',
  'Brushing teeth',
  'Taking a shower',
  'Walking a dog',
  'Playing catch',
  'Hugging',
  'Waving hello',
  'Pointing',
  'Clapping',
  'Sneezing',
  'Yawning',
  'Crying',
  'Laughing',
  'Thinking',
  'Singing',

  // Emotions & Expressions
  'A happy person',
  'A sad person',
  'An angry person',
  'A scared person',
  'A surprised person',
  'Someone confused',
  'Someone excited',
  'Someone tired',
  'Someone embarrassed',
  'Someone proud',

  // Animals doing things
  'A cat sleeping',
  'A dog playing',
  'A bird flying',
  'A fish swimming',
  'A monkey climbing',
  'An elephant spraying water',
  'A penguin sliding',
  'A snake slithering',
  'A bear waving',
  'A frog jumping',

  // Situations & Scenes
  'A birthday party',
  'A picnic',
  'A camping trip',
  'A beach day',
  'A rainy day',
  'A snowy day',
  'Sunset',
  'Sunrise',
  'A rainbow',
  'Fireworks',
  'A concert',
  'A wedding',
  'A graduation',
  'Halloween',
  'Christmas morning',
  'A snowman',
  'Building a sandcastle',
  'Flying a kite',
  'A bonfire',
  'Stargazing',

  // Sports & Games
  'Playing basketball',
  'Playing soccer',
  'Playing baseball',
  'Playing tennis',
  'Playing golf',
  'Playing football',
  'Bowling',
  'Ice skating',
  'Skiing',
  'Surfing',
  'Rock climbing',
  'Skateboarding',
  'Rollerblading',
  'Hopscotch',
  'Jump rope',
  'Tug of war',

  // Jobs & Professions
  'A doctor',
  'A teacher',
  'A firefighter',
  'A police officer',
  'A chef',
  'An astronaut',
  'A pilot',
  'A dentist',
  'A musician',
  'A painter',
  'A construction worker',
  'A mail carrier',
  'A farmer',

  // Objects in use
  'An umbrella in the rain',
  'A balloon floating',
  'A kite flying',
  'A campfire',
  'A birthday cake',
  'An ice cream cone melting',
  'A broken window',
  'A ringing phone',
  'A television',
  'A computer',
  'Headphones',
  'A camera',
  'Sunglasses',
  'A backpack',

  // Nature & Weather
  'A tree',
  'A flower',
  'Mountains',
  'The ocean',
  'A river',
  'A waterfall',
  'Lightning',
  'A tornado',
  'Clouds',
  'The sun',
  'The moon',
  'Stars',
  'A cactus',

  // Food & Meals
  'Eating pizza',
  'A hamburger',
  'A hot dog',
  'Ice cream',
  'A birthday cake',
  'Spaghetti',
  'A sandwich',
  'Popcorn',
  'French fries',
  'A taco',
  'Breakfast',
  'Dinner time',

  // Transportation
  'A car',
  'A bicycle',
  'An airplane',
  'A boat',
  'A train',
  'A helicopter',
  'A rocket',
  'A motorcycle',
  'A school bus',
  'A fire truck',

  // Buildings & Places
  'A house',
  'A school',
  'A hospital',
  'A castle',
  'A lighthouse',
  'A church',
  'A barn',
  'The Eiffel Tower',
  'A pyramid',
  'A bridge',

  // Household Items
  'A chair',
  'A table',
  'A bed',
  'A lamp',
  'A clock',
  'A mirror',
  'A picture frame',
  'A door',
  'A window',
  'Stairs',

  // Miscellaneous
  'A ghost',
  'A robot',
  'A superhero',
  'A princess',
  'A king',
  'A pirate',
  'A cowboy',
  'A dinosaur',
  'A dragon',
  'An alien',
  'A monster',
  'A wizard',
  'A mermaid',
  'A unicorn',
];

// Story prompts for Story Remix
export const storyPrompts = [
  'Once upon a time in a magical kingdom...',
  'It was a dark and stormy night when suddenly...',
  'In the year 2525, humans discovered...',
  'The detective knew something was wrong when...',
  'Nobody expected what would happen at the party...',
  'The treasure map led them to...',
  'On the first day of school, they found...',
  'The secret door in the basement opened to reveal...',
  'When the clock struck midnight...',
  'The last thing they remembered was...',
];

// Story twist prompts
export const storyTwists = [
  'Add a character who is actually a time traveler',
  'Introduce a magical object that changes everything',
  'Make something explode (but everyone is okay)',
  'Add an unexpected animal character',
  'Reveal that it was all a dream... or was it?',
  'Introduce a villain with a silly weakness',
  'Add a dance party',
  'Make someone discover they have superpowers',
  'Add a mysterious stranger with important news',
  'Include a chase scene',
];

// Fact or Fiction question categories
export const factCategories = [
  'Tell us about an embarrassing moment',
  'Share an unusual talent or skill you have',
  'Describe a strange food you\'ve eaten',
  'Tell us about a weird dream you remember',
  'Share an interesting place you\'ve visited',
  'Describe something you\'re afraid of',
  'Tell us about a time you got lost',
  'Share a hidden talent',
  'Describe your most unusual pet or animal encounter',
  'Tell us about a time you broke something',
];

// Mission Mayhem mission descriptions
export const missions = [
  'Explore the Ancient Temple',
  'Hack the Mainframe',
  'Retrieve the Secret Documents',
  'Disable the Security System',
  'Rescue the Hostage',
  'Plant the Tracking Device',
  'Steal the Rare Artifact',
  'Decode the Message',
  'Sabotage the Enemy Base',
  'Escape the Facility',
];
